-- MySQL Script generated by MySQL Workbench
-- Thu Sep 11 21:15:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema akces-dms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `akces-dms` ;

-- -----------------------------------------------------
-- Schema akces-dms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `akces-dms` ;
USE `akces-dms` ;

-- -----------------------------------------------------
-- Table `akces-dms`.`tanks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akces-dms`.`tanks` ;

CREATE TABLE IF NOT EXISTS `akces-dms`.`tanks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tank_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akces-dms`.`measurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akces-dms`.`measurements` ;

CREATE TABLE IF NOT EXISTS `akces-dms`.`measurements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `tank_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_measurements_tanks_idx` (`tank_id` ASC) VISIBLE,
  CONSTRAINT `fk_measurements_tanks`
    FOREIGN KEY (`tank_id`)
    REFERENCES `akces-dms`.`tanks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `akces-dms`.`dosing_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akces-dms`.`dosing_events` ;

CREATE TABLE IF NOT EXISTS `akces-dms`.`dosing_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value_start` FLOAT NOT NULL,
  `value_end` FLOAT NOT NULL,
  `timestamp_start` DATETIME NOT NULL,
  `timestamp_end` DATETIME NOT NULL,
  `is_collision` TINYINT NOT NULL,
  `value_difference` FLOAT NOT NULL,
  `collision_value_difference` FLOAT NOT NULL,
  `time_difference` INT NOT NULL,
  `dosing_speed_factor` FLOAT NOT NULL,
  `tank_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dosing_events_tanks1_idx` (`tank_id` ASC) VISIBLE,
  CONSTRAINT `fk_dosing_events_tanks1`
    FOREIGN KEY (`tank_id`)
    REFERENCES `akces-dms`.`tanks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akces-dms`.`batches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akces-dms`.`batches` ;

CREATE TABLE IF NOT EXISTS `akces-dms`.`batches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp_start` DATETIME NOT NULL,
  `timestamp_end` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `akces-dms`.`batch_dosing_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akces-dms`.`batch_dosing_event` ;

CREATE TABLE IF NOT EXISTS `akces-dms`.`batch_dosing_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `batch_id` INT NOT NULL,
  `dosing_event_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_batch_dosing_event_batches1_idx` (`batch_id` ASC) VISIBLE,
  INDEX `fk_batch_dosing_event_dosing_events1_idx` (`dosing_event_id` ASC) VISIBLE,
  CONSTRAINT `fk_batch_dosing_event_batches1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `akces-dms`.`batches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batch_dosing_event_dosing_events1`
    FOREIGN KEY (`dosing_event_id`)
    REFERENCES `akces-dms`.`dosing_events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
